name: Docker Build and Push
description: Build and push Docker image

inputs:
  context:
    description: Build context
    required: false
    default: '.'
  push:
    description: Push image
    required: false
    default: 'true'
  tags:
    description: Image tags
    required: true

runs:
  using: composite
  steps:
    - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
