name: Setup Terraform
description: Setup Terraform CLI with optional Terraform Cloud token

inputs:
  terraform-version:
    description: Terraform version
    required: false
    default: '1.14.3'
  token:
    description: Terraform Cloud API token
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      with:
        terraform_version: ${{ inputs.terraform-version }}
        cli_config_credentials_token: ${{ inputs.token }}
