name: Dev - deploy comment

on:
  workflow_call:

jobs:
  deploy-dev:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'dev deploy')
    runs-on: self-hosted

    steps:
      - name: React to Comment
        uses: brevisdev/.github/.github/actions/github-script@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentId = context.payload.comment.id;
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              content: 'rocket'
            });

      - name: Get PR Information
        id: get-branch
        uses: brevisdev/.github/.github/actions/github-script@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.issue.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            core.setOutput("branch", pullRequest.head.ref);

      - name: Checkout PR Branch
        uses: brevisdev/.github/.github/actions/checkout@main
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - name: Trigger Deployment
        run: |
          gh workflow run deploy-dev.yaml \
            --ref ${{ steps.get-branch.outputs.branch }} \
            --field branch=${{ steps.get-branch.outputs.branch }}
        env:
          GH_TOKEN: ${{ github.token }}
